Repository puppetlabs/cat-github-actions, pull requests merged in 2023-04, with the labels that each got.

#31 (CONT-404) Address deprecation warnings
  .github/workflows/gem_release.yml
  .github/workflows/module_release.yml
  .github/workflows/module_release_prep.yml
Labels: maintenance

#33 (Maint) - Add module release title
  .github/workflows/module_release.yml
Labels: maintenance

#34 (MAINT) Normalize Gem Versions
  .github/workflows/gem_release_prep.yml
Labels: enhancement

#35 (MAINT) Move PUPPET_GEM_VERSION
  .github/workflows/gem_ci.yml
Labels: bug

#36 (maint) - Update pdk image
  .github/workflows/module_release.yml
  .github/workflows/module_release_prep.yml
Labels: maintenance

#37 Maint update pdk release image
  .github/workflows/module_release.yml
Labels: maintenance

#38 (MAINT) honour puppet_version input
  .github/workflows/gem_acceptance.yml
Labels: bug

#39 (maint) - update pdk image
  .github/workflows/module_release.yml
  .github/workflows/module_release_prep.yml
Labels: maintenance

#40 (MAINT) Set PUPPET_GEM_VERSION
  .github/workflows/module_acceptance.yml
Labels: maintenance
