Repository puppetlabs/cat-github-actions, pull requests merged in 2024-05, with the labels that each got.

#85 (CAT-1829) - Update to dynamic checkout ref gem_ci
  .github/workflows/gem_ci.yml
Labels: maintenance

#87 (bug) - Fix broken conditional on windows
  .github/workflows/gem_ci.yml
Labels: maintenance

#88 workflow fixes and improvements
  .github/workflows/gem_ci.yml
  .github/workflows/labeller.yml
  .github/workflows/mend_ruby.yml
  .github/workflows/module_acceptance.yml
  .github/workflows/module_release.yml
  .github/workflows/tooling_mend_ruby.yml
  example/module/ci.yml
  example/module/labeller.yml
  example/module/mend.yml
  example/module/nightly.yml
  example/module/release.yml
  example/module/release_prep.yml
Labels: enhancement

#90 (bug) - gem_ci.yml fix Unrecognized named-value: secrets
  .github/workflows/gem_ci.yml
Labels: bug
