Repository puppetlabs/cat-github-actions, pull requests merged in 2024-10, with the labels that each got.

#113 (MAINT) - update set output to use github output
  .github/workflows/workflow-restarter.yml
Labels: maintenance

#114 (CAT-2013) Implement shellcheck in ci workflow
  .github/workflows/gem_ci.yml
Labels: enhancement

#116 (CAT-2094) Add shellcheck to module_ci workflow
  .github/workflows/module_ci.yml
Labels: enhancement

#118 Make workflow-restarter docs more clear
  docs/workflow-restarter.md
Labels: maintenance

#119 (MAINT) Update readme and reviewdog docs
  README.md
  docs/reviewdog-shellcheck.md
Labels: documentation
