Repository puppetlabs/cat-github-actions, pull requests merged in 2024-06, with the labels that each got.

#92 (MAIN) Updating examples
  example/module/labeller.yml
  example/module/mend.yml
Labels: maintenance

#93 (maint) - Remove redundant conditional checkout
  .github/workflows/gem_ci.yml
Labels: maintenance

#94 (maint) - Remove redundant conditional checkout
  .github/workflows/tooling_mend_ruby.yml
Labels: maintenance

#96 Revert pull_request_target changes
  .github/workflows/mend_ruby.yml
Labels: bug

#98 CAT-1918 : Adding check for version from metadata.json
  .github/workflows/module_release.yml
Labels: enhancement
